import Head from 'next/head';
import styles from '../styles/Home.module.scss';
import { PostCard, Categories, PostWidget} from '../components';
import { getPosts } from '../services';

export default function Home({ posts }) {
  return (
    <main className={styles.wrapper}>

      <Head>
        <title>Manguito&apos;s Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <div className={styles.posts}>
          {posts.map((post) => <PostCard post={post.node} key={post.title} />)}
        </div>

        <aside className={styles.sidebar}>

            <PostWidget/>
            <Categories/>

        </aside>

    </main>
  )
}

export async function getStaticProps() {

  const posts = (await getPosts()) || [];

  return{
    props: { posts }
  } 

}
